<?php return array (
  1 => 
  array (
    'id' => '1',
    'shortcut' => 0,
    'position' => 1,
    'name' => 'General',
    'sub_name' => 'Make basic settings for your website',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:settings?group=general',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/1.png',
    'active_name' => 'general',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  2 => 
  array (
    'id' => '2',
    'shortcut' => 0,
    'position' => 2,
    'name' => 'E-mail',
    'sub_name' => 'Email settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:settings?group=email',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/8.png',
    'active_name' => 'email',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  3 => 
  array (
    'id' => '3',
    'shortcut' => 0,
    'position' => 3,
    'name' => 'Advanced',
    'sub_name' => 'Additional settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:settings?group=advanced',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/2.png',
    'active_name' => 'advanced',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  4 => 
  array (
    'id' => '4',
    'shortcut' => 0,
    'position' => 4,
    'name' => 'Files',
    'sub_name' => 'File management',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:settings?group=files',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/9.png',
    'active_name' => 'files',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  5 => 
  array (
    'id' => '5',
    'shortcut' => 0,
    'position' => 5,
    'name' => 'Login & Register',
    'sub_name' => 'Manage the access control to your website',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:settings?group=login',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/15.png',
    'active_name' => 'login',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  // 6 => 
  // array (
  //   'id' => '6',
  //   'shortcut' => 0,
  //   'position' => 6,
  //   'name' => 'Language',
  //   'sub_name' => 'Choice of language and translations',
  //   'link' => NULL,
  //   'mw_link' => NULL,
  //   'dt_link' => 'view:content/action:settings?group=language',
  //   'dt_temp_link' => NULL,
  //   'icon' => NULL,
  //   'img' => 'admin-logo/website-settings/3.png',
  //   'active_name' => 'language',
  //   'module_name' => NULL,
  //   'data_link' => NULL,
  //   'data_title' => NULL,
  //   'onclick' => NULL
  // ),
  // 7 => 
  // array (
  //   'id' => '7',
  //   'shortcut' => 0,
  //   'position' => 7,
  //   'name' => 'Connect to DRM',
  //   'sub_name' => 'Connect to DRM',
  //   'link' => NULL,
  //   'mw_link' => NULL,
  //   'dt_link' => NULL,
  //   'dt_temp_link' => NULL,
  //   'icon' => NULL,
  //   'img' => 'admin-logo/website-settings/01.png',
  //   'active_name' => 'Connect to DRM',
  //   'module_name' => NULL,
  //   'data_link' => NULL,
  //   'data_title' => NULL,
  //   'onclick' => 'onclick="connectDRM()"'
  // ),
  8 => 
  array (
    'id' => '8',
    'shortcut' => 0,
    'position' => 8,
    'name' => 'Users',
    'sub_name' => 'Users settings',
    'link' => NULL,
    'mw_link' => 'load_module:users',
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/4.png',
    'active_name' => 'users',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  9 => 
  array (
    'id' => '9',
    'shortcut' => 0,
    'position' => 9,
    'name' => 'Contact-form',
    'sub_name' => 'Contact-form settings',
    'link' => 'https://drm.software/admin/contact_forms',
    'mw_link' => NULL,
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/contact.png',
    'active_name' => 'Contact-form',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  10 => 
  array (
    'id' => '10',
    'shortcut' => 0,
    'position' => 10,
    'name' => 'Comments',
    'sub_name' => 'Comments settings',
    'link' => NULL,
    'mw_link' => 'load_module:comments',
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/16.png',
    'active_name' => 'comments',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  11 => 
  array (
    'id' => '11',
    'shortcut' => 0,
    'position' => 11,
    'name' => 'Menu',
    'sub_name' => 'Menu settings',
    'link' => NULL,
    'mw_link' => 'load_module:menu',
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/5.png',
    'active_name' => 'menu',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  12 => 
  array (
    'id' => '12',
    'shortcut' => 0,
    'position' => 12,
    'name' => 'Dropfunnels',
    'sub_name' => 'Dropfunnels settings',
    'link' => 'https://drm.software/admin/email_marketings',
    'mw_link' => NULL,
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/02.png',
    'active_name' => 'Dropfunnels',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  13 => 
  array (
    'id' => '13',
    'shortcut' => 0,
    'position' => 13,
    'name' => 'Backup',
    'sub_name' => 'Backup V2 settings',
    'link' => NULL,
    'mw_link' => 'load_module:admin__backup_v2',
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/6.png',
    'active_name' => 'admin__backup_v2',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  14 => 
  array (
    'id' => '14',
    'shortcut' => 0,
    'position' => 14,
    'name' => 'Captcha',
    'sub_name' => 'Captcha settings',
    'link' => NULL,
    'mw_link' => 'load_module:captcha',
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/12.png',
    'active_name' => 'captcha',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  15 => 
  array (
    'id' => '15',
    'shortcut' => 0,
    'position' => 15,
    'name' => 'Testimonials',
    'sub_name' => 'Testimonials settings',
    'link' => NULL,
    'mw_link' => 'load_module:testimonials',
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/17.png',
    'active_name' => 'testimonials',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  16 => 
  array (
    'id' => '16',
    'shortcut' => 0,
    'position' => 16,
    'name' => 'Search Hits',
    'sub_name' => 'Search Hits settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:settings?group=searchhits',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/7.png',
    'active_name' => 'searchhits',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  17 => 
  array (
    'id' => '17',
    'shortcut' => 0,
    'position' => 17,
    'name' => 'Post Limit',
    'sub_name' => 'Post Limit settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:settings?group=postlimit',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/13.png',
    'active_name' => 'postlimit',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  18 => 
  array (
    'id' => '18',
    'shortcut' => 0,
    'position' => 18,
    'name' => 'SEO Settings',
    'sub_name' => 'Search Engine Optimization Settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:settings?group=seo',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/seo.png',
    'active_name' => 'seo',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  19 => 
  array (
    'id' => '19',
    'shortcut' => 1,
    'position' => 19,
    'name' => 'Pages',
    'sub_name' => 'Manage and create your pages',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:pages',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/pages.png',
    'active_name' => 'pages',
    'module_name' => NULL,
    'data_link' => 'view:content#action=new:page',
    'data_title' => 'Add new page',
    'onclick' => NULL
  ),
  20 => 
  array (
    'id' => '20',
    'shortcut' => 1,
    'position' => 20,
    'name' => 'Blog posts',
    'sub_name' => 'Manage and create your blog posts',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:posts',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/blog-posts.png',
    'active_name' => 'posts',
    'module_name' => NULL,
    'data_link' => 'view:content#action=new:post',
    'data_title' => 'Add new post',
    'onclick' => NULL
  ),
  21 => 
  array (
    'id' => '21',
    'shortcut' => 1,
    'position' => 21,
    'name' => 'Categories',
    'sub_name' => 'Manage and create your categories',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:content/action:categories',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/website-settings/category.png',
    'active_name' => 'categories',
    'module_name' => NULL,
    'data_link' => 'view:content#action=new:category',
    'data_title' => 'Add new category',
    'onclick' => NULL
  ),
  22 => 
  array (
    'id' => '22',
    'shortcut' => 0,
    'position' => 22,
    'name' => 'Performance Settings',
    'sub_name' => 'Speed up your website',
    'link' => NULL,
    'mw_link' => "group=performance",
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => "admin-logo/website-settings/performance.png",
    'active_name' => 'Performancesetting',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  23 => 
  array (
    'id' => '23',
    'shortcut' => 0,
    'position' => 23,
    'name' => 'Image optimize',
    'sub_name' => 'Image optimize settings',
    'link' => NULL,
    'mw_link' => "load_module:image_optimize",
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => "admin-logo/website-settings/imageoptimize.png",
    'active_name' => 'setting',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
  24 =>
  array(
    'id' => '24',
    'shortcut' => 0,
    'position' => 24,
    'name' => 'Display Blog Post',
    'sub_name' => 'Choose the condition for display post on frontend',
    'link' => NULL,
    'mw_link' => "group=display_blog",
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => "admin-logo/website-settings/13.png",
    'active_name' => 'setting',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
    'onclick' => NULL
  ),
);