<?php return array (
  1 => 
  array (
    'id' => '1',
    'shortcut' => '0',
    'position' => 0,
    'name' => 'Basic settings',
    'sub_name' => 'Basic store settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:options/?group=general',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/1.png',
    'active_name' => 'general',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  2 => 
  array (
    'id' => '2',
    'shortcut' => '0',
    'position' => 1,
    'name' => 'Rabattcodes',
    'sub_name' => 'Creating and managing coupon codes',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:options/?group=coupons',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/6.png',
    'active_name' => 'coupons',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  3 => 
  array (
    'id' => '3',
    'shortcut' => '0',
    'position' => 2,
    'name' => 'Versandeinstellungen',
    'sub_name' => 'Delivery methods and suppliers',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' =>'view:shop/action:options/?group=shipping',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/11.png',
    'active_name' => 'shipping',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  4 => 
  array (
    'id' => '4',
    'shortcut' => '0',
    'position' => 3,
    'name' => 'Zahlungsanbieter',
    'sub_name' => 'Select and set up a payment provider',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:options/?group=payments',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/2.png',
    'active_name' => 'payments',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  5 => 
  array (
    'id' => '5',
    'shortcut' => '0',
    'position' => 4,
    'name' => 'Services (Cross-Selling)',
    'sub_name' => 'Hier kannst du Cross-Sellings (z.B. Geschenkverpackung, Batterien, etc.) erstellen und verwalten',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:productUpselling',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/12.png',
    'active_name' => 'productUpselling',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  6 => 
  array (
    'id' => '6',
    'shortcut' => '0',
    'position' => 5,
    'name' => 'Thank You Pages',
    'sub_name' => ' Managing Thank You Pages',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:thank_you_pages',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/3.png',
    'active_name' => 'thank_you_pages',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  7 => 
  array (
    'id' => '7',
    'shortcut' => '0',
    'position' => 6,
    'name' => 'Angebote (inkl. Countdown)',
    'sub_name' => 'Managing Angebote (inkl. Countdown)',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/load_module:shop__offers',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/13.png',
    'active_name' => 'shop__offers',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  8 => 
  array (
    'id' => '8',
    'shortcut' => '0',
    'position' => 7,
    'name' => 'Preisvergleichsportale',
    'sub_name' => 'Managing Preisvergleichsportale',
    'link' => 'https://drm.software/admin/channel-products?channel=10',
    'mw_link' => NULL,
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/4.png',
    'active_name' => 'channel-products',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  9 => 
  array (
    'id' => '9',
    'shortcut' => '0',
    'position' => 8,
    'name' => 'Lieferbedingungen',
    'sub_name' => 'Lieferbedingungen settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/load_module:legals__shipping-info',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/9.png',
    'active_name' => 'legals__shipping-info',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  11 => 
  array (
    'id' => '11',
    'shortcut' => '0',
    'position' => 10,
    'name' => 'Checkout',
    'sub_name' => 'Checkout settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => NULL,
    'dt_temp_link' => 'checkout',
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/5.png',
    'active_name' => 'checkout',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  12 => 
  array (
    'id' => '12',
    'shortcut' => '0',
    'position' => 11,
    'name' => 'Lagerbestand anzeigen',
    'sub_name' => 'Du kannst den Lagerbestand im Shop veröffentlichen oder verbergen',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:options/?group=quantity',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/10.png',
    'active_name' => 'quantity',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  13 => 
  array (
    'id' => '13',
    'shortcut' => '0',
    'position' => 12,
    'name' => 'Tax rates',
    'sub_name' => 'You can set a taxes for different countries',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:options/?group=tax_rates',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/7.png',
    'active_name' => 'tax_rates',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  14 => 
  array (
    'id' => '14',
    'shortcut' => '0',
    'position' => 13,
    'name' => 'Other settings',
    'sub_name' => 'Other settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:options/?group=other',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/15.png',
    'active_name' => 'other',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  15 => 
  array (
    'id' => '15',
    'shortcut' => '1',
    'position' => 0,
    'name' => 'Products',
    'sub_name' => 'Manage your products or add new ones',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:products',
    'dt_temp_link' => NULL,
    'icon' => '',
    'img' => 'admin-logo/shop-settings/products.png',
    'active_name' => 'products',
    'module_name' => 'shop.products',
    'data_link' => 'view:content#action=new:product',
    'data_title' => 'Add new product',
  ),
  16 => 
  array (
    'id' => '16',
    'shortcut' => '1',
    'position' => 1,
    'name' => 'Shop Categories',
    'sub_name' => 'Manage and create your shop categories',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:shop_categories',
    'dt_temp_link' => NULL,
    'icon' => '',
    'img' => 'admin-logo/shop-settings/shop_category.png',
    'active_name' => 'shop_categories',
    'module_name' => NULL,
    'data_link' => 'view:shop/action:shop_categories#action=editcategory:0',
    'data_title' => 'Add new category',
  ),
  17 => 
  array (
    'id' => '17',
    'shortcut' => '1',
    'position' => 2,
    'name' => 'Orders',
    'sub_name' => 'Manage my orders',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:orders#orderstype=completed',
    'dt_temp_link' => NULL,
    'icon' => '',
    'img' => 'admin-logo/shop-settings/orders.png',
    'active_name' => 'cmplt_cart',
    'module_name' => 'shop.orders',
    'data_link' => 'javascript:window.open(\'https://drm.software/admin/drm_all_orders/add\', \'_blank\').focus();',
    'data_title' => 'Add order',
  ),
  18 => 
  array (
    'id' => '18',
    'shortcut' => '1',
    'position' => 3,
    'name' => 'Abandoned Carts',
    'sub_name' => 'Abandoned Carts Settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:orders#orderstype=carts',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/abandon-cart.png',
    'active_name' => 'abn_cart',
    'module_name' => 'shop.orders',
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  19 => 
  array (
    'id' => '19',
    'shortcut' => '1',
    'position' => 4,
    'name' => 'Customer management',
    'sub_name' => 'Manage your customer master data',
    'link' => 'javascript:window.open(\'https://drm.software/admin/drm_all_customers?filter=customers\', \'_blank\').focus();',
    'mw_link' => NULL,
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/client.png',
    'active_name' => 'clients',
    'module_name' => 'shop.customers',
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  20 => 
  array (
    'id' => '20',
    'shortcut' => '0',
    'position' => 20,
    'name' => 'Subscription Product',
    'sub_name' => 'Subscription Product Settings',
    'link' => NULL,
    'mw_link' => 'group=subProduct',
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/subscriptionproduct.png',
    'active_name' => 'settings',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  21 => 
  array (
    'id' => '21',
    'shortcut' => '0',
    'position' => 21,
    'name' => 'Handlingtime',
    'sub_name' => 'Delivery time according to handling time',
    'link' => NULL,
    'mw_link' => 'group=handlingtime',
    'dt_link' => NULL,
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/11.png',
    'active_name' => 'settings',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  22 => 
  array (
    'id' => '22',
    'shortcut' => '0',
    'position' => 22,
    'name' => 'Configure legal texts',
    'sub_name' => 'Configure legal texts Settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:configure_legal_texts',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/14.png',
    'active_name' => 'settings',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  23 => 
  array (
    'id' => '23',
    'shortcut' => '0',
    'position' => 23,
    'name' => 'Instagram Feed',
    'sub_name' => 'Instagram Feed Settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:instagram',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/insta.png',
    'active_name' => 'settings',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),
  24 => 
  array(
    'id' => '24',
    'shortcut' => '0',
    'position' => 24,
    'name' => 'Bundle Product',
    'sub_name' => 'Bundle Product Settings',
    'link' => NULL,
    'mw_link' => NULL,
    'dt_link' => 'view:shop/action:bundle_product',
    'dt_temp_link' => NULL,
    'icon' => NULL,
    'img' => 'admin-logo/shop-settings/1.png',
    'active_name' => 'settings',
    'module_name' => NULL,
    'data_link' => NULL,
    'data_title' => NULL,
  ),  
);